-- Ajuste manual de preço por hospedagem ("Gerenciar Preços").
-- Snapshot do ajuste aplicado (desconto/adicional) a uma hospedagem.
-- Modos mutuamente exclusivos:
--   * valor_diaria  -> sobrescreve o valor das diárias existentes (qtd inalterada)
--   * valor_desconto-> ajuste absoluto sobre o total
--   * porcentagem   -> ajuste percentual sobre o total
-- O sinal (desconto/adicional) e todo o cálculo são feitos no front-end.
-- Executar manualmente no PostgreSQL (o projeto não usa Flyway/Liquibase/JPA).

CREATE TABLE public.hospedagem_novo_preco (
    id                 int8 GENERATED BY DEFAULT AS IDENTITY
                           ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE )
                           NOT NULL,
    fk_hospedagem      int8 NOT NULL,
    quantidade_diarias int4 NULL,
    quantidade_pessoas int4 NULL,
    valor_diaria       float8 NULL,
    porcentagem        int4 NULL,
    valor_desconto     float8 NULL,
    fk_funcionario     int8 NULL,
    data_hora_registro timestamp DEFAULT now() NULL,
    CONSTRAINT pk_hospedagem_novo_preco PRIMARY KEY (id),
    CONSTRAINT fk_hospedagem_novo_preco_hospedagem
        FOREIGN KEY (fk_hospedagem) REFERENCES public.hospedagem(id),
    CONSTRAINT fk_hospedagem_novo_preco_funcionario
        FOREIGN KEY (fk_funcionario) REFERENCES public.funcionario(id)
);

CREATE INDEX idx_hosp_novo_preco_fk_hospedagem
    ON public.hospedagem_novo_preco (fk_hospedagem);
